### ISSUE TITLE
Save last used dimension and units in journal object

### ISSUE THREAD

**Issue by quozl** [sugarlabs/convert#13]
Reproducer: start, change dimension and units, stop, restart from journal entry.

Expected: dimension and units preserved.

Observed: dimension and units are reset to Length - Cables.

At the same time, add a reset button to restore dimension and units to defaults.

**Comment by Aniket21mathur** [comment]
I am sorry I am not able to understand what exactly do you mean by journal entry and journal object?
Thanks!

**Comment by quozl** [comment]
https://help.sugarlabs.org/en/journal.html should help to explain.  Every Sugar activity creates a Journal Entry.  Internally, a Journal Entry is implemented as a Journal Object in Python.  Look at the activity API sources in the toolkit.

**Comment by Aniket21mathur** [comment]
@quozl I am sorry but still I am  not able to understand what's the difference between Journal entry and user's activity instance data directory.I don't know much about journal entry but as per my knowledge of user's activity instance data directory won't it be better to save this dimensions and units at user's activity instance data directory.I worked on it and  made a pull request I request you to once review it and decide :smile: .Thanks!

**Comment by quozl** [comment]
@Aniket21mathur, the difference is profound and yet subtle.

* Journal Entry
  * what a user of Sugar is to think of as a file,
  * shown by the Journal (F5 key),
  * created automatically by running an activity,
  * resuming the entry resumes the activity in the same state as when it was stopped,
  * implemented as files and metadata in a private directory managed by the Sugar Datastore component, using a D-Bus RPC API.
* activity instance data directory,
  * unique to an activity,
  * a directory into which an activity may read and write data,
  * best used for activity state that is permanent, such as Terminal font size,

I suggest you read one of the guides to writing Sugar activities.

**Comment by kushagra98** [comment]
Is this issue still open?
