### ISSUE TITLE
Value entry does not need spin buttons

### ISSUE THREAD

**Issue by quozl** [sugarlabs/convert#14]
To the left of the Convert button is a value entry widget.

On the GTK+ 2 version, this was rendered with spin buttons; up and down arrows vertically aligned.

On the GTK+ 3 version, this is rendered with spin buttons; - and + horizontally aligned.

However, spin buttons are not needed, are a distraction, and so a plain unadorned text entry can be used instead.

**Comment by chimosky** [comment]
> However, spin buttons are not needed, are a distraction, and so a plain unadorned text entry can be used instead.

Respectfully disagree, the spin buttons are the only way - *currently* - to increase the value of the unit being converted from and it can contain any value up to 10000000000 . When you say plain unadorned text, what do you mean?.

**Comment by quozl** [comment]
That is not what I see; I can increase the value by clicking on the number, and typing a new number.  That's quicker and more accurate than pressing the spin buttons.  I don't think this entry widget needs the spin buttons.

**Comment by chimosky** [comment]
I now understand.
