### ISSUE TITLE
Result widget shows superfluous text cursor when clicked

### ISSUE THREAD

**Issue by quozl** [sugarlabs/convert#15]
Clicking in the result field shows a vertical bar cursor, also known as a text caret.  Arrow keys can be used to move the cursor.  The cursor may be mistaken for a digit.

![convert-a](https://user-images.githubusercontent.com/2936481/39221780-58e0ef1e-487c-11e8-9c3d-f71d132160d8.png)

**Comment by chimosky** [comment]
I don't know why all the previous commits are still showing here even after being merged. 
#17

**Comment by quozl** [comment]
That's unrelated to the issue.  See my answer in pull request.

Also, it seems the issue may be caused by missing text highlight when selected.  When you select an area of the result field, only the cursor is shown.  The selected area is not shown.

**Comment by chimosky** [comment]
The `set_selectable` been enabled is the only way text gotten from the label can be copied, a simple work around could be simply converting to a unit, text highlight also works fine.

**Comment by quozl** [comment]
> ... text highlight also works fine

That's interesting, thanks.

Text highlight doesn't work on Ubuntu 16.04 with Sugar 0.112.  Method; place mouse cursor within text, press and hold mouse button, drag mouse cursor over text, release mouse button.  No highlight is shown.  A text cursor caret is shown briefly at the press position.  If ctrl+c is pressed, the Frame shows a text clipping of the invisibly-selected text.

Perhaps the missing highlight related to the Sugar widget theme.  What version of GTK+ are you using?  In my tests it is 3.18.9.

**Comment by chimosky** [comment]
> What version of GTK+ are you using?

I'm using version 3.22.30

**Comment by quozl** [comment]
Thanks.  I've tested just now on Ubuntu 18.04 which has 3.22.0 and the selected text highlight does occur.

![convert-b](https://user-images.githubusercontent.com/2936481/39386692-203d9b8c-4ab9-11e8-9923-3da5abdef912.png)

So it seems this issue was inside GTK+ and has since been fixed.
