### ISSUE TITLE
Convert button should be automatic

### ISSUE THREAD

**Issue by quozl** [sugarlabs/convert#16]
Reproducer: enter a value for conversion, press convert, enter a different value.

Problem: result displayed is inconsistent with entered value.

Proposed solution: remove the convert button and do the conversion on each change to the value.

**Comment by quozl** [comment]
Also, just pressing enter after typing a number doesn't do convert, as of 7bb29e4f670b2dae1dfdd645fe0c7c6b83c75049.

**Comment by Aniket21mathur** [comment]
@quozl convert button pressing is an event from the user that signals that the user has finished entering the value to be converted.How  it can be automatic? There must be some event that should be triggered 
from user side to start conversion like some key press or clicking conversion button.Thanks!

**Comment by quozl** [comment]
Yes.  It can be automatic by using the _insert-text_ signal.  Pressing enter will cause the _activate_ signal.

**Comment by quozl** [comment]
@chimosky, please review this issue and pull request https://github.com/sugarlabs/convert/pull/22

* should the conversion be on each change to the value, or when enter key is pressed?
