### ISSUE TITLE
Activity review comments

### ISSUE THREAD

**Issue by quozl** [sugarlabs/convert#24]
* [x] starting the activity shows no units selected,
* [x] switching between unit ranges using the toolbar doesn't select any default units,
* [x] entering 9 shows `9.0 ~ -9.00000000001`, it should be `9 ~ 9`,
* [x] there's no tooltip for the swap units button,
* [x] swap of units changes to a different value with too many significant digits (e.g. select inches to millimetres, enter 1.0, click on swap, the entry box now contains 0.0393700787402 and the conversion 0.00155000310001)

**Comment by nswarup14** [comment]
@quozl @chimosky 
What work is still left in this issue?
I am currently reading up on the PR (#26) and to understand the work still left.

Thanks

**Comment by quozl** [comment]
Please test each and let me know what you observe.

**Comment by quozl** [comment]
I've tested each, as of 5ad65539e4eb6f2391d72481d1850bbc0c1464ec, and they are all fixed.

**Comment by nswarup14** [comment]
@quozl 
Tested as of https://github.com/sugarlabs/convert/pull/32/commits/ad63d02e5f8f39b3eab86d7e83ff3d56f8a2a26d and all the issues listed above work correctly.

The issue can be closed.

**Comment by quozl** [comment]
Thanks.
