### ISSUE TITLE
Two entry boxes would remove need for swap button

### ISSUE THREAD

**Issue by quozl** [sugarlabs/convert#25]
At the moment the activity has;

* source unit (a menu),
* destination unit (a menu),
* source value (centered entry),
* source value and destination value (centered label),

| unit | swap | unit |
| ---- | ---- | ---- |
| | value | |
| | value - value  | |

An alternate design could be;

* source value (an entry on the left of display),
* source unit (a menu to the right or below the source value),
* destination value (an entry on the right of display).
* destination unit,

| value | unit | | value | unit |
| ---- | ---- | ---- | ---- | ---- |

This would;

* make it clear what the unit is for each value,
* allow changes to the destination value,
* remove the need for a swap button.

Discuss?

**Comment by leonardcj** [comment]
Sounds like a better design layout to me.  Would not appear to have any real impact on current i18n/L10n one way or the other, but raises the question of improvement.  It does make a certain left-to-right (LTR) assumption that may not be true in all languages.  I'm not personally familiar enough with right-to-left (RTL) languages to know how they display units.  I'm not sure if there are RTL languages that might have different conventions for value/unit or unit/value ordering.  I wonder if there is another Linux unit conversion tool known to have good i18n you might peek at to look at their i18n tweaks?

**Comment by leonardcj** [comment]
Sounds like a better design layout to me.  Would not appear to have any real impact on current i18n/L10n one way or the other, but raises the question of improvement.  It does make a certain left-to-right (LTR) assumption that may not be true in all languages.  I'm not personally familiar enough with right-to-left (RTL) languages to know how they display units.  I'm not sure if there are RTL languages that might have different conventions for value/unit or unit/value ordering.  I wonder if there is another Linux unit conversion tool known to have good i18n you might peek at to look at their i18n tweaks?

**Comment by chimosky** [comment]
I think the source unit coming before the source value would be great and I agree with you, it's a better layout design and removes the need for the swap button

**Comment by salunkheketki19** [comment]
Hello Sir,
I want to work on this issue can you please explain me the exact issue in detail?

**Comment by Aniket21mathur** [comment]
Agreed. A better design layout, less confusing and easy to use!
